set_languages("c++23")
add_rules("mode.debug")
set_toolchains("msvc")

add_repositories("MrowrLib https://github.com/MrowrLib/package-repo.git")
add_repositories("ModdingFramework https://github.com/ModdingFramework/package-repo.git")
add_requires("StringFormatting")
add_requires("Memory")
add_requires("Logging")
add_requires("zydis")
add_requires("xbyak")
add_requires("spdlog")

target("Assembly")
    set_kind("library")
    add_headerfiles("include/(**.h)")
    add_includedirs("include", {public = true})
    add_packages("zydis")
    add_packages("xbyak")
    add_packages("Memory")
    add_packages("Logging")

target("Example")
    set_kind("binary")
    add_files("Example.cpp")
    add_deps("Assembly")
    add_imports("Assembly")
    add_packages("StringFormatting")
    add_packages("zydis")
    add_packages("xbyak")
    add_packages("Memory")
    add_packages("Logging")
    add_packages("spdlog")
